#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(__dirname, "..");
const repoRoot = resolve(webRoot, "..");
const slidesSrc = join(repoRoot, "slides");
const themeFile = join(repoRoot, "themes", "tech.css");
const publicSlidesDir = join(webRoot, "public", "slides");
const generatedFile = join(webRoot, "src", "slides.generated.ts");

const SKIP_DIRS = new Set(["assets"]);

if (!existsSync(slidesSrc)) {
  console.error(`[build-slides] slides directory not found: ${slidesSrc}`);
  process.exit(1);
}

rmSync(publicSlidesDir, { recursive: true, force: true });
mkdirSync(publicSlidesDir, { recursive: true });

const assetsSrc = join(slidesSrc, "assets");
if (existsSync(assetsSrc)) {
  cpSync(assetsSrc, join(publicSlidesDir, "assets"), { recursive: true });
}

const entries = readdirSync(slidesSrc, { withFileTypes: true })
  .filter((e) => e.isDirectory() && !SKIP_DIRS.has(e.name))
  .map((e) => e.name)
  .sort();

const slides = [];

for (const slug of entries) {
  const mdPath = join(slidesSrc, slug, `${slug}.md`);
  if (!existsSync(mdPath)) {
    console.warn(`[build-slides] skip ${slug}: missing ${slug}.md`);
    continue;
  }

  const outDir = join(publicSlidesDir, slug);
  mkdirSync(outDir, { recursive: true });
  const outHtml = join(outDir, `${slug}.html`);

  console.log(`[build-slides] building ${slug}`);
  const result = spawnSync(
    "npx",
    [
      "--yes",
      "@marp-team/marp-cli@latest",
      "--theme-set",
      themeFile,
      "--html",
      mdPath,
      "-o",
      outHtml,
    ],
    { stdio: "inherit", cwd: repoRoot },
  );
  if (result.status !== 0) {
    console.error(`[build-slides] marp-cli failed for ${slug}`);
    process.exit(result.status ?? 1);
  }

  const meta = parseFrontmatter(readFileSync(mdPath, "utf8"));
  const title = meta.title ?? extractTitle(readFileSync(mdPath, "utf8")) ?? slug;
  const description = meta.description ?? extractSubtitle(readFileSync(mdPath, "utf8")) ?? "";
  const updatedAt = lastCommitDate(mdPath) ?? statSync(mdPath).mtime.toISOString().slice(0, 10);

  slides.push({
    slug,
    title,
    description,
    href: `/slides/${slug}/${slug}.html`,
    updatedAt,
  });
}

slides.sort((a, b) => (a.updatedAt < b.updatedAt ? 1 : a.updatedAt > b.updatedAt ? -1 : a.slug.localeCompare(b.slug)));

const banner = "// This file is generated by scripts/build-slides.mjs. Do not edit.\n";
const body = `export interface SlideEntry {
  slug: string;
  title: string;
  description: string;
  href: string;
  updatedAt: string;
}

export const slides: SlideEntry[] = ${JSON.stringify(slides, null, 2)};
`;
writeFileSync(generatedFile, banner + body);
console.log(`[build-slides] generated ${slides.length} entries → src/slides.generated.ts`);

function parseFrontmatter(src) {
  if (!src.startsWith("---")) return {};
  const end = src.indexOf("\n---", 3);
  if (end === -1) return {};
  const block = src.slice(3, end).trim();
  const out = {};
  for (const line of block.split("\n")) {
    const m = line.match(/^([A-Za-z0-9_-]+)\s*:\s*(.+?)\s*$/);
    if (!m) continue;
    out[m[1]] = m[2].replace(/^['"]|['"]$/g, "");
  }
  return out;
}

function extractTitle(src) {
  const body = stripFrontmatter(src);
  const m = body.match(/^#\s+(.+?)\s*$/m);
  return m ? m[1].trim() : null;
}

function extractSubtitle(src) {
  const body = stripFrontmatter(src);
  const afterH1 = body.split(/^#\s+.+$/m)[1] ?? "";
  for (const raw of afterH1.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith("<!--") || line.startsWith("---")) continue;
    if (line.startsWith("<")) continue;
    if (line.startsWith("![")) continue;
    return stripInlineMarkdown(line);
  }
  return null;
}

function lastCommitDate(filePath) {
  const result = spawnSync("git", ["log", "-1", "--format=%cs", "--", filePath], {
    cwd: repoRoot,
    encoding: "utf8",
  });
  if (result.status !== 0) return null;
  const out = result.stdout.trim();
  return out || null;
}

function stripInlineMarkdown(line) {
  return line
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .trim();
}

function stripFrontmatter(src) {
  if (!src.startsWith("---")) return src;
  const end = src.indexOf("\n---", 3);
  return end === -1 ? src : src.slice(end + 4);
}
